# 6) NLA Exercise 8.2
Write a function mgs(A) that computes a reduced $\hat{Q}\hat{R}$ factorization using the modified Gram-Schmidt orthogonalization

In [1]:
import numpy as np

def mgs(A):
  assert np.issubdtype(np.float64, A.dtype)
  #Initialize V0
  q = A.T[0]/np.linalg.norm(A.T[0])
  v = A.T[0]
  Q = []
  Q.append(q)

  # Calculate Q Matrix
  for i in range(1, A.shape[1]):
    v_new = A.T[i] 
    for qq in Q:
      v_new = v_new - (A.T[i].dot(qq))*qq
    q = v_new/np.linalg.norm(v_new)
    Q.append(q)
  Q = np.array(Q)

  # Calculate R Matrix
  R=np.zeros((A.shape))
  for i in range(A.shape[1]):
    for j in range(i+1):
      R[j][i] = Q[j].dot(A.T[i])

  m = min(R.shape)
  R = R[:m, :m]
  return Q.T, R

A = np.array([[1.0, 0, 1], [2, 1, 0]]).T
Q, R = mgs(A)

print(Q)
print(R)
print(Q.dot(R))

[[ 0.70710678  0.57735027]
 [ 0.          0.57735027]
 [ 0.70710678 -0.57735027]]
[[1.41421356 1.41421356]
 [0.         1.73205081]]
[[ 1.0000000e+00  2.0000000e+00]
 [ 0.0000000e+00  1.0000000e+00]
 [ 1.0000000e+00 -1.7026819e-16]]


# 7)
Apply the [Q,R]=mgs(A) function you have written in the previous problem to
the following matrix. Check the orthogonality of Q matrix by calculating norm(Q’*Q-eye(2)). Compare the value returned by mgs vs the one returned by the qr function in Matlab.
 $$\begin{bmatrix}
0.700000 & 0.70711\\
0.70001 & 0.70711
\end{bmatrix}$$ 

R) Matrices are equal but have an inverted signal

In [2]:
A = np.array([[0.7, 0.70711], [0.70001, 0.70711]])
Q, R = mgs(A)
print(Q)
print(R)


print(np.linalg.norm(Q.T.dot(Q)-np.identity(2)))
Q, R,  = np.linalg.qr(A, mode='reduced')
print(Q)
print(R)

[[ 0.70710173  0.70711183]
 [ 0.70711183 -0.70710173]]
[[9.89956565e-01 1.00000455e+00]
 [0.00000000e+00 7.14286165e-06]]
3.254726094493924e-11
[[-0.70710173 -0.70711183]
 [-0.70711183  0.70710173]]
[[-9.89956565e-01 -1.00000455e+00]
 [ 0.00000000e+00 -7.14283864e-06]]


# 9) NLA 10.2
Write a function

a) W, R = house(A) that computes QR factorization using the householder reflector method

b) Q = formQ(W) that retrieves the Q coeficients

In [3]:
def house(A):
  R = A.copy()
  W = np.zeros(A.shape)
  
  for k in range(R.shape[1]):
    X = R[k:, k].copy()
    e = np.zeros(R.shape[0]-k)
    e[0] = 1.0
    vk = np.sign(X[0])*np.linalg.norm(X)*e + X
    vk = vk/np.linalg.norm(vk)
    W[k:, k] = vk
    R[k:, k:] = R[k:, k:]+ np.outer(-2*vk, vk.T.dot(R[k:, k:]))


  n = min(R.shape)
  R = R[:n, :n]
  return W, R


A = np.array([[1.0, 0, 1], [2, 1, 0]]).T
W, R = house(A)
print(W)
print(R)

def formQ(W):
  W=W.copy()
  m = max(W.shape)
  n = min(W.shape)
  Q = np.identity(m)
  for i in range(n-1, -1, -1):
    q = W[i:,i].T.dot(Q[i:,:])
    q = np.outer(2*W[i:,i].T, q)
    Q[i:m,:] = Q[i:m,:]-q

  m = min(W.shape)
  Q = Q[:, :m]
  return Q

Q = formQ(W)
print(Q)
print(Q.dot(R))

[[ 0.92387953  0.        ]
 [ 0.          0.88807383]
 [ 0.38268343 -0.45970084]]
[[-1.41421356 -1.41421356]
 [ 0.         -1.73205081]]
[[-0.70710678 -0.57735027]
 [ 0.         -0.57735027]
 [-0.70710678  0.57735027]]
[[ 1.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -6.61280946e-16]]


# 10) 10.3

Compare the previous results with the built-in functions for python on the following matrix
 $$\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 7\\
4 & 2 & 3\\
4 & 2 & 2
\end{bmatrix}$$ 


R) We can see that in all cases We are able to recover Z from QR

In [4]:
Z = np.array([
    [1.0, 2, 3],
    [4, 5, 6],
    [7, 8, 7],
    [4, 2, 3],
    [4, 2, 2],
])

print("\nMy QR")
Q, R = mgs(Z)
print(Q)
print(R)
print(Q.dot(R))

print("\nPython QR")
Q, R = np.linalg.qr(Z)
print(Q)
print(R)
print(Q.dot(R))

#####################
print("\nMy House")
W, R = house(Z)
print(W)
print(R)
Q = formQ(W)
print(Q)
print(Q.dot(R))

print("\nPython House")
h, tau = np.linalg.qr(Z, mode='raw')
print(h)
print(tau)



My QR
[[ 0.10101525  0.31617307  0.5419969 ]
 [ 0.40406102  0.3533699   0.51618752]
 [ 0.70710678  0.39056673 -0.52479065]
 [ 0.40406102 -0.55795248  0.38714064]
 [ 0.40406102 -0.55795248 -0.12044376]]
[[9.89949494 9.49543392 9.69746443]
 [0.         3.29191961 3.01294337]
 [0.         0.         1.97011572]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 7.]
 [4. 2. 3.]
 [4. 2. 2.]]

Python QR
[[-0.10101525 -0.31617307  0.5419969 ]
 [-0.40406102 -0.3533699   0.51618752]
 [-0.70710678 -0.39056673 -0.52479065]
 [-0.40406102  0.55795248  0.38714064]
 [-0.40406102  0.55795248 -0.12044376]]
[[-9.89949494 -9.49543392 -9.69746443]
 [ 0.         -3.29191961 -3.01294337]
 [ 0.          0.          1.97011572]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 7.]
 [4. 2. 3.]
 [4. 2. 2.]]

My House
[[ 0.74196201  0.          0.        ]
 [ 0.27229225  0.78655506  0.        ]
 [ 0.47651145  0.11919725 -0.9800408 ]
 [ 0.27229225 -0.42844087  0.18420552]
 [ 0.27229225 -0.42844087 -0.07475533]]
[[-9.89949494 -9.49543392 -9.697464